#!/bin/bash

cd $(dirname $0)/..

function die() {
  echo "$1"
  exit 1
}

MONGO_PORT=27017
which nc &>/dev/null && nc -vz localhost $MONGO_PORT 2>/dev/null || die "Can't find MongoDB on port $MONGO_PORT (using: nc -vz localhost $MONGO_PORT)"

which sm2 &>/dev/null || die "Can't find Service Manager"

sm2 --start ITSA_SUBSC_MIN $@
sleep 5

sm2 --stop INCOME_TAX_SUBSCRIPTION

sleep 5
sbt "run 9560 -Dplay.http.router=testOnlyDoNotUseInAppConf.Routes"
